import json
import time
import os
import io
import sys
import asyncio
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.responses import FileResponse
from openai import OpenAI
from telegram import Update
from telegram.ext import ApplicationBuilder, MessageHandler, ContextTypes, filters

# --- Environment Variables ---
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
PUBLIC_HOST_URL = os.getenv("PUBLIC_HOST_URL")  # e.g., https://my-data-analyst-bot.onrender.com
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

LOG_FILE = "run.jsonl"
full_log_url = f"{PUBLIC_HOST_URL.rstrip('/')}/{LOG_FILE}" if PUBLIC_HOST_URL else "URL_NOT_SET"

# Point the OpenAI client to Gemini's compatibility endpoint
client = OpenAI(
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key=GEMINI_API_KEY
)

conversation_history = {}
ptb_application = None

# --- Helper: Safe Python Execution Tool ---
def execute_python_code(code: str) -> str:
    """Executes python code generated by the LLM to calculate data or fetch APIs."""
    old_stdout = sys.stdout
    sys.stdout = buffer = io.StringIO()
    try:
        # Provide common data analysis tools to the execution environment
        local_env = {}
        exec(f"import json\nimport math\nimport statistics\nimport pandas as pd\nimport httpx\n{code}", {}, local_env)
        output = buffer.getvalue()
        return output if output.strip() else "Code executed successfully with no print output."
    except Exception as e:
        return f"Error executing code: {str(e)}"
    finally:
        sys.stdout = old_stdout

# --- Logging ---
def log_event(event: dict):
    event["timestamp"] = time.time()
    with open(LOG_FILE, "a") as f:
        f.write(json.dumps(event) + "\n")

# --- Agent Loop ---
async def process_with_agent(chat_id: int, user_text: str) -> str:
    history = conversation_history.setdefault(chat_id, [])
    
    # Initialize chat history with the System Prompt if empty
    if not history:
        system_prompt = (
            "You are an expert data analyst AI. The user will ask data-analysis questions and provide an EXACT JSON schema to reply with. "
            "You MUST reply with ONLY that exact JSON object. No markdown, no explanations.\n\n"
            f"If the user asks for a log_url, you must use EXACTLY this URL: {full_log_url}\n\n"
            "If you need to calculate math, fetch an API, or analyze data, write Python code and use the 'run_python_code' tool to print the answer. "
            "Then, use that printed answer to construct the final JSON."
        )
        history.append({"role": "system", "content": system_prompt})
        
    history.append({"role": "user", "content": user_text})

    # Define the tool available to the LLM
    tools = [{
        "type": "function",
        "function": {
            "name": "run_python_code",
            "description": "Execute Python code to fetch URLs using httpx, calculate statistics, or process data. You MUST use print() to output the results so you can read them.",
            "parameters": {
                "type": "object",
                "properties": {
                    "code": {"type": "string", "description": "Python code to execute. Must include print statements."}
                },
                "required": ["code"]
            }
        }
    }]

    # Run the Agent Loop (Max 4 iterations to prevent infinite loops)
    for _ in range(4):
        response = client.chat.completions.create(
            model="gemini-2.5-flash",
            messages=history,
            tools=tools
        )
        
        msg = response.choices[0].message
        
        # We need to manually convert the message object to a dict to append to history cleanly
        msg_dict = {"role": "assistant", "content": msg.content}
        if msg.tool_calls:
            msg_dict["tool_calls"] = [{"id": tc.id, "type": "function", "function": {"name": tc.function.name, "arguments": tc.function.arguments}} for tc in msg.tool_calls]
        history.append(msg_dict)

        # If the LLM decided to use the Python tool
        if msg.tool_calls:
            for tc in msg.tool_calls:
                if tc.function.name == "run_python_code":
                    args = json.loads(tc.function.arguments)
                    print(f"\n[Agent executing code]:\n{args['code']}\n")
                    
                    # Run the code and get the result
                    result = execute_python_code(args["code"])
                    
                    # Append the tool result back into the context
                    history.append({
                        "role": "tool",
                        "tool_call_id": tc.id,
                        "name": tc.function.name,
                        "content": result
                    })
        else:
            # If there are no tool calls, the LLM has generated the final answer.
            return msg.content or ""
            
    return '{"error": "Agent loop limit reached"}'

# --- Telegram Handler ---
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat_id = update.effective_chat.id
    user_text = update.message.text
    log_event({"type": "incoming", "chat_id": chat_id, "text": user_text})

    # Get the LLM Agent's response
    reply_text = await process_with_agent(chat_id, user_text)

    # Clean up the output to ensure strict JSON compliance
    try:
        # Strip markdown fences if the LLM accidentally added them
        start = reply_text.find("{")
        end = reply_text.rfind("}")
        if start != -1 and end != -1:
            clean_json_str = reply_text[start:end+1]
            parsed = json.loads(clean_json_str)
            final_reply = json.dumps(parsed)
        else:
            final_reply = reply_text # Fallback
    except json.JSONDecodeError:
        final_reply = reply_text

    log_event({"type": "outgoing", "chat_id": chat_id, "text": final_reply})
    await update.message.reply_text(final_reply)

# --- FastAPI Setup for Render (Serves the log & runs Telegram in background) ---
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup: Initialize and start the Telegram bot
    global ptb_application
    ptb_application = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()
    ptb_application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    
    await ptb_application.initialize()
    await ptb_application.start()
    await ptb_application.updater.start_polling()
    print("Telegram Bot Polling started!")
    
    yield
    
    # Shutdown: Cleanly stop the Telegram bot
    await ptb_application.updater.stop()
    await ptb_application.stop()
    await ptb_application.shutdown()

app = FastAPI(lifespan=lifespan)

@app.get("/run.jsonl")
async def serve_log():
    # If the file doesn't exist yet, return an empty file rather than a 404 error
    if not os.path.exists(LOG_FILE):
        open(LOG_FILE, 'a').close() 
    return FileResponse(LOG_FILE, media_type="application/jsonlines")

@app.get("/")
async def health_check():
    return {"status": "Bot is running and logging."}
